<?xml version="1.0" encoding="UTF-8"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    <xacro:include filename="inertial_macros.xacro"/>

    <!-- PROPERTIES -->
    <xacro:property name="chassis_length" value="0.15"/>
    <xacro:property name="chassis_width" value="0.10"/>
    <xacro:property name="chassis_height" value="0.03"/>
    <xacro:property name="wheel_mass" value="0.015"/>
    <xacro:property name="wheel_radius" value="0.02"/>
    <xacro:property name="wheel_thickness" value="0.02"/>
    <xacro:property name="wheel_offset_y" value="0.06"/>
    <xacro:property name="wheel_offset_z" value="-0.015"/>
    <xacro:property name="caster_radius" value="0.01"/>
    <xacro:property name="caster_wheel_mass" value="0.02"/>
    <xacro:property name="caster_wheel_offset_x" value="0.11"/>
    

    <material name="white">
        <color rgba="1 1 1 1" />
    </material>

    <material name="orange">
        <color rgba="1 0.3 0.1 1"/>
    </material>

    <material name="blue">
        <color rgba="0.2 0.2 1 1"/>
    </material>

    <material name="black">
        <color rgba="0 0 0 1"/>
    </material>

    <material name="red">
        <color rgba="1 0 0 1"/>
    </material>
        
    <!--  BASE LINK -->
    <link name="base_link"></link>

    <joint name="base_footprint_joint" type="fixed">
        <parent link="base_link"/>
        <child link="base_footprint"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </joint>

    <link name="base_footprint"></link>
    
    <!-- CHASSIS LINK -->
    <joint name="chassis_joint" type="fixed">
        <parent link="base_link"/>
        <child link="chassis_link"/>
        <origin xyz="-0.01 0.0 0.0" rpy="0.0 0.0 0.0"/>
    </joint>

    <link name="chassis_link">
        <visual>
            <origin xyz="${chassis_length/2} 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
            </geometry>
            <material name="white"/>
        </visual>
        <collision>
            <origin xyz="${chassis_length/2} 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="0.25" x="${chassis_length}" y="${chassis_width}" z="${chassis_height}">
            <origin xyz="${chassis_length/2} 0 ${chassis_height/2}" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <gazebo reference="chassis_link">
        <material>Gazebo/White</material>
    </gazebo>

    <!-- WHEELS -->
    <joint name="left_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="left_wheel_link"/>
        <origin xyz="0.0 ${wheel_offset_y} ${wheel_offset_z}" rpy="-${pi/2} 0.0 0.0"/>
        <axis xyz="0 0 1"/>
    </joint>

    <link name="left_wheel_link">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <geometry>
                <!-- Changed length to prevent wheel slippage -->
                <cylinder radius="${wheel_radius}" length="0.0001"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_thickness}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <gazebo reference="left_wheel_link">
        <material>Gazebo/Black</material>
    </gazebo>

    <joint name="right_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="right_wheel_link"/>
        <origin xyz="0.0 ${-wheel_offset_y} ${wheel_offset_z}" rpy="${pi/2} 0.0 0.0"/>
        <axis xyz="0 0 -1"/>
    </joint>

    <link name="right_wheel_link">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <geometry>
                <!-- Changed length to prevent wheel slippage -->
                <cylinder radius="${wheel_radius}" length="0.0001"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_thickness}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <gazebo reference="right_wheel_link">
        <material>Gazebo/Black</material>
    </gazebo>

    <!-- CASTER WHEEL -->
    <joint name="caster_wheel_joint" type="fixed">
        <parent link="base_link"/>
        <child link="caster_wheel_link"/>
        <origin xyz="${caster_wheel_offset_x} 0 ${wheel_offset_z}"/>
    </joint>

    <link name="caster_wheel_link">
        <visual>
            <geometry>
                <sphere radius="${wheel_radius}"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${wheel_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_sphere mass="${caster_wheel_mass}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_sphere>
    </link>

    <gazebo reference="caster_wheel_link">
        <material>Gazebo/Black</material>
        <mu1>0.0001</mu1>
        <mu2>0.0002</mu2>
    </gazebo>

</robot>